name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
         
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    -
      name: Login to GCR
      uses: docker/login-action@v3
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 363.0.0'
        service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true
        
    - name: Auth With GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}'

    - name: Build and push Docker image to Artifact Registry
      env:
        ARTIFACT_REGISTRY_REGION: us-central1 
        REGION: "us-central1" 
        GAR_LOCATION: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/react-frontend
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/react-frontend/connectmate .
        docker tag us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/react-frontend/connectmate us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/react-frontend/connectmate:$GITHUB_SHA
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/react-frontend/connectmate:$GITHUB_SHA
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/react-frontend/connectmate:latest



    - name: Deploy to Cloud Run
      run: |
        # Create a JSON file for GCP (Google Cloud Platform)
        echo '{
          "GCP_PROJECT_ID": "${{ secrets.GCP_PROJECT_ID }}",
          "GCP_PROJECT_NAME": "${{ secrets.GCP_PROJECT_NAME }}",
          "GCP_PROJECT_NUMBER": "${{ secrets.GCP_PROJECT_NUMBER }}",
          "GCR_SERVICE_ACCOUNT_KEY": "${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}"
quote> }' > env-vars.json

        cat env-vars.json
        
        gcloud run deploy connectmate-front \
          --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/react-frontend/connectmate \
          --env-vars-file=env-vars.json \
          --platform=managed \
          --port=3000 \
          --region=us-central1 \
          --allow-unauthenticated \
          --memory 1G
